// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCM.Data;

#nullable disable

namespace PCM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240808135354_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCM.Models.Collection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomBoolean1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomBoolean2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomBoolean3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectionId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("PCM.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomBoolean1Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomBoolean2Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomBoolean3Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate1Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate2Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDate3Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt1Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt2Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInt3Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText1Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText2Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomMultilineText3Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString1Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString2Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomString3Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ItemId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ItemId1");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PCM.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PCM.Models.Item", b =>
                {
                    b.HasOne("PCM.Models.Collection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCM.Models.Item", null)
                        .WithMany("Items")
                        .HasForeignKey("ItemId1");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("PCM.Models.Collection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PCM.Models.Item", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
